### ISSUE TITLE
[BUG] Progress bar is fixed at 240px

### ISSUE THREAD

**Issue by linanwx** [jdanielmourao/obsidian-sanctum#169] opened 2022-06-30 15:34 UTC
I love this plugin. Thanks to the author.
But there's a little problem when I use it.
The attribute of progress is fixed at 240px.
<img width="281" alt="截屏2022-06-30 23 26 52" src="https://user-images.githubusercontent.com/16589958/176716305-44cf5e29-c0d3-4b53-b3c9-b0e74e781eb0.png">
It looks strange in some cases.
<img width="338" alt="截屏2022-06-30 23 27 22" src="https://user-images.githubusercontent.com/16589958/176716683-70b26291-052a-4f0c-9fe1-d2cbbf63ef4e.png">
I use the following css snippet code to overwrite it. So now it behaves normally. But I wonder if this is right way?
`
progress {
    width: 0px !important;
}
`

**Comment by jdanielmourao** [comment] 2022-07-20 14:47
Hi! Could you please elaborate in what specific instances it doesn't work as intended? I'm not sure I understand what's going on in that screenshot. Are those audio recordings?

**Comment by linanwx** [comment] 2022-07-22 10:46
> Hi! Could you please elaborate in what specific instances it doesn't work as intended? I'm not sure I understand what's going on in that screenshot. Are those audio recordings?

Yes, those are audio recordings in preview mode. The component style of the audio is not from the original but from a plugin called [Media Extended](https://github.com/aidenlx/media-extended). If this plugin is not installed, there will be no problem.

So I think maybe it's the plugin problem? Maybe this plugin uses the wrong Element or Classes?

**Comment by jdanielmourao** [comment] 2022-07-23 16:33
Could you show me the markdown so I get an idea of the order things are written in?

**Comment by jdanielmourao** [comment] 2022-07-23 17:36
If you use this as a snippet, it seems to do the trick:
```md
.markdown-preview-view .plyr--audio progress.plyr__progress__buffer {
	display: none;
}```
It is indeed related to the plugin.

**Comment by jdanielmourao** [comment] 2022-07-23 17:37
I'm closing the issue since the plugin itself isn't supported by the theme.

**Closed by jdanielmourao** 2022-07-23 17:37 UTC
Labels: bug/issue

**Comment by linanwx** [comment] 2022-07-24 08:39
Since that plugin has too many problems, I rewrite a new plugin to replace it. Now it worked fine with Sanctum Theme.
Well, anyway, thanks for your reply.
