### ISSUE TITLE
Bug : Cursor dissapears on the Code Block

### ISSUE THREAD

**Issue by ujjwal3067** [jdanielmourao/obsidian-sanctum#8] opened 2021-10-16 14:37 UTC
Vim Cursor ( normal mode ) dissapears when in code block. I think it's  because code block is  in foreground and cursor seems go be in background.

https://user-images.githubusercontent.com/28984548/137591536-573063cc-bc15-4c3d-a70f-3693ea5ee4e0.mov

**Comment by jdanielmourao** [comment] 2021-10-16 23:17
Hi there! 👋
I've detected this issue as well! It also happens when using a mouse, and trying to select text: both the caret and the selection color disappear. I'll push it higher on priority, and should be fixed next release!
Thanks for your feedback, and I hope you enjoy Sanctum!

**Comment by jdanielmourao** [comment] 2021-10-18 23:29
@ujjwal3067 Pls check if the issue is resolved! :)

**Comment by ujjwal3067** [comment] 2021-10-18 23:59
Works perfect! I like the attention to details in this theme especially the vim cursor is actually block size. 
Thanks !

**Closed** 2021-10-19 00:20 UTC
